### ISSUE TITLE
[BUG] Missing style for basic tables in markdown rendering

### ISSUE THREAD

**Issue by smortex** [opensearch-project/oui#1194]
**Describe the bug**

When rendering tables in a markdown document e.g. in an OpenSearch Dashboards' notebook, the table does not have any CSS on top of the CSS reset, making it barely readable: all data is cluttered as there is no space between fields, making it hard to see where a column ends and the next one starts.

**To Reproduce**
1. Go to 'Observability', 'Notebook'
2. Create a Notebook
3. Add a paragraph
4. Add this sample content:

```
%md

Foo

| Mesure             | Avant   | Après  | Ratio |
|--------------------|---------|--------|-------|
| Backup incrémental |     3mn |   20mn | × 7   |
| Backup complet     |     1h  |     8h | × 8   |
| Débit des backups  | 380kB/s | 62kB/s | ÷ 6   |

Bar
```

**Expected behavior**

Columns should be clearly separated, and there should be spacing above and bellow the table.

**Screenshots**

Current rendering of the above example (note the missing spacing between cells and after the table):

![screenshot of a table hard to read](https://github.com/opensearch-project/oui/assets/148721/fa574ef8-4ddc-4bad-865e-8850cbdbcf5c)

Adding some CSS can help, as an experiment I added this style to my browser to do some testing:

```css
.euiText table {
  border-top: 2px solid #000;
  border-bottom: 2px solid #000;
  margin: 1em auto;
}

.euiText table th {
  border-bottom: 1px solid #000;
}

.euiText table td {
  padding: 0 1em;
}
```

![example with the above css](https://github.com/opensearch-project/oui/assets/148721/38fb7d6e-53b1-43da-9302-78ec9f300dd5)

**Host/Environment (please complete the following information):**
 - OUI Version: 1.3.0 I guess (what ships with the latest OSD)
 - OSD Version (if applicable): 2.11.1
 - OS: n/a
 - Browser and version n/a (Firefox)
